### ISSUE TITLE
contributors

### ISSUE THREAD

**Issue by EnumaElish123** [JerryMazeyu/MCM#1]
To add the contributors

**Comment by EnumaElish123** [comment]
@all-contributors 
please add @JerryMazeyu for design, data, ideas.
please add @tiezhuguangtailang for data, code.
please add @ggxxding for data, code.
please add @LiangRichard13 for data, code, video.
please add @EnumaElish123 for data, test.
please add @LX945794759 for projectManagement, eventOrganizing.

**Comment by EnumaElish123** [comment]
@all-contributors please add @JerryMazeyu for design, data, ideas.

**Comment by JerryMazeyu** [comment]
@all-contributors
please add @JerryMazeyu for design, data, ideas.
please add @tiezhuguangtailang for data, code.
please add @ggxxding for data, code.
please add @LiangRichard13 for data, code, video.
please add @EnumaElish123 for data, test.
please add @LX945794759 for projectManagement, eventOrganizing.

**Comment by JerryMazeyu** [comment]
@all-contributors
please add @JerryMazeyu for design, data, ideas.
please add @tiezhuguangtailang for data, code.
please add @ggxxding for data, code.
please add @LiangRichard13 for data, code, video.
please add @EnumaElish123 for data, test.
please add @LX945794759 for projectManagement, eventOrganizing.

**Comment by JerryMazeyu** [comment]
@all-contributors please add @ggxxding for data, code

**Comment by JerryMazeyu** [comment]
@all-contributors please add @LiangRichard13 for data, code, video
