### ISSUE TITLE
model权重和论文报告

### ISSUE THREAD

**Issue by mazai-xiangji** [JerryMazeyu/MCM#10]
你好，想问一下是否会发布模型权重及详细的论文或者技术报告

**Comment by JerryMazeyu** [comment]
你好，相关的论文还在撰写中，模型权重在OpenXLab的官网上是有的：https://openxlab.org.cn/models/detail/kevin77/MCM

**Comment by zhangbaijin** [comment]
你好，模型权重在OpenXLab似乎没有
