### ISSUE TITLE
where the checkpoints files?

### ISSUE THREAD

**Issue by Zhengyea** [JerryMazeyu/MCM#8]
e:/MCM/MCM\src/backend/checkpoints/sentence-transformer does not appear to have a file named config.json. Checkout 'https://huggingface.co/e:/MCM/MCM\src/backend/checkpoints/sentence-transformer/None' for available files.

**Comment by JerryMazeyu** [comment]
我们近期会将测评结果陆续发布到Github库中，本项目使用的Checkpoints会在近期上传到OpenXlab模型中心。
We will be releasing the results to the Github library shortly, and the checkpoints used in this project will be uploaded to the OpenXlab model center shortly.
https://openxlab.org.cn/models/detail/kevin77/MCM
